kind: ConfigMap
apiVersion: v1
metadata:
  name: pgvector-initsql
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    psql -U postgres -c "CREATE DATABASE ${POSTGRES_DBNAME};"
    psql -U postgres -d ${POSTGRES_DBNAME} -c "CREATE EXTENSION VECTOR;"
