kind: Secret
apiVersion: v1
metadata:
  name: pgvector
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
data:
  user: {{ .Values.secret.user | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
  host: {{ .Values.secret.host | b64enc | quote }}
  port: {{ .Values.secret.port | b64enc | quote }}
  dbname: {{ .Values.secret.dbname | b64enc | quote }}
  jdbc-uri: {{ printf "jdbc:postgresql://%s.%s:%s/%s?password=%s&user=%s" .Values.secret.host .Release.Namespace .Values.secret.port .Values.secret.dbname .Values.secret.password .Values.secret.user | b64enc | quote }}
  uri: {{ printf "postgresql://%s:%s@%s.%s:%s/%s" .Values.secret.user .Values.secret.password .Values.secret.host .Release.Namespace .Values.secret.port .Values.secret.dbname | b64enc | quote }}
type: Opaque
