name: Package and Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/publish-helm-charts.yaml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Package charts
        run: |
          mkdir -p gh-pages
          for chart in helm/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              helm package "$chart" -d gh-pages
            fi
          done

      - name: Generate Helm index
        run: |
          helm repo index gh-pages --url https://yuvalturg.github.io/testrepo --merge gh-pages/index.yaml

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update Helm chart repo" || echo "No changes to commit"
          git push origin gh-pages
